---
title: "one_var_model"
author: "irena"
date: "9/30/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(ROCR)
library(ggplot2)
library(randomForest)
library(dplyr)
library(iml)
library(ROSE)
library(reshape2)
library(MLmetrics)
library(rstatix)

```


load bufo.RData

random forest model 1000 replicates
```{r}

fvarrf <- bufo_rfvar
d <- bufolist


outc <- "type"
envst <- append(fvarrf, outc)
   
fvarrfimprf <- list()
fvarrfmrf <- list()
fvarrfpredrf <- list()
fvarrftrainsetrf <- list()
tune <- list()

myauct <- list()
tlable <- list()
################
auctrain <- list()
auctest <- list()
###############   
for(i in 1:1000)
  {
     
    
    m <- d[[i]][ , envst]
    m$type <- factor(m$type)

   set.seed(110)
   Train <- createDataPartition(m$type, p = .7,list = FALSE,times = 1)

   training <- m[Train, ]
   
   
   training$type <- factor(training$type, levels = c("rk","random"))
   testing = m[ -Train, ]
   testing$type <- factor(testing$type, levels = c("rk","random"))
   
    training_pv <- preProcess(training, method = c("center", "scale"))
    trainTransformed <- predict(training_pv, training)
    training <- trainTransformed

    testing_pv <- preProcess(testing, method = c("center", "scale"))
    testTransformed <- predict(testing_pv, testing)
    testing <- testTransformed


   grid <- expand.grid(mtry = seq(1, length(fvarrf), by = 1))


#with rose  
train_control = trainControl(method="repeatedcv", number=2, repeats=5,sampling = "rose", savePredictions = T,summaryFunction = twoClassSummary, classProbs = TRUE)
 

  set.seed(100)
  
    mrf = caret::train(training[,fvarrf],training[,outc],method="rf",  trControl=train_control,importance=TRUE,metric = 'ROC',ntree = 500, na.action = na.omit,tuneGrid = grid)
  
  
   #training
  Fitcrftr<- predict(mrf, training)
  conrftr <- caret::confusionMatrix(Fitcrftr,training$type,positive ="rk",mode="everything")
  Fitprftr <- predict(mrf, training,type = "prob")
  rocobrftr <- prediction(Fitprftr$rk, training$type, label.ordering = c("random", "rk"))
  
  #auc roc training
  aucrocrftr <- performance(rocobrftr,"auc")
  auc1tr <- aucrocrftr@y.values[[1]]

#aucpr training
  aucprrftr <- performance(rocobrftr,"aucpr")
  auc2tr <- aucprrftr@y.values[[1]]
  
   
   #testing
  Fitcrf<- predict(mrf, testing)
  conrf <- confusionMatrix(Fitcrf, testing$type,positive = "rk",mode = "everything")
  Fitprf <- predict(mrf, testing,type = "prob")
  rocobrf <- prediction(Fitprf$rk, testing$type, label.ordering = c("random", "rk"))

#auc roc
  aucrocrf <- performance(rocobrf,"auc")
  auc1 <- aucrocrf@y.values[[1]]

#aucpr
  aucprrf <- performance(rocobrf,"aucpr")
  auc2 <- aucprrf@y.values[[1]]

  vrf <- varImp(mrf)
  vrf <- as.data.frame(vrf$importance) 
  vrf <- select(vrf,1)
  names(vrf)[1] <- "fvarrf"
  vrft <- data.frame(t(vrf))
###########################################################################  
  fvarrfimprf[[i]] <- vrft
  fvarrfmrf[[i]] <- mrf
  fvarrfpredrf[[i]] <- Fitprf[,1]
  fvarrftrainsetrf[[i]] <- training
####################################################################  
  vec <- c(auc1tr, auc2tr,auc1, auc2)
  myauct[[i]] <- vec
  tune[[i]] <- mrf$bestTune
################  
auctrain[[i]] <- auc1tr
auctest[[i]] <- auc1
####################   
}
auct <- as.data.frame(do.call(cbind, myauct))
aucct <- t(auct)
colnames(aucct) <- c("rfauc_train","rfaucpr_train","rfauc_test","rfaucpr_test")
 
aucct <- data.frame(aucct) 


p <- aucct
pt <- data.frame(t(p))


pt$mean <- apply(p,2,mean)
pt$sd <- apply(p,2,sd)

pt2c <- pt[,c(1001,1002)]
rft <- as.data.frame(t(pt2c))

trainauc <- rft[1,1]
trainaucpr <- rft[1,2]
trainaucsd <- rft[2,1]
trainaucprsd <- rft[2,2]

testauc <- rft[1,3]
testaucpr <- rft[1,4]
testaucsd <- rft[2,3]
testaucprsd <- rft[2,4]

basetest <- prop.table(table(testing$type))[[1]]
basetr <- prop.table(table(training$type))[[1]]
aucdff <- trainauc-testauc
aucprdff <- trainaucpr-testaucpr


AUC <- c(trainauc,testauc,aucdff,trainaucsd,testaucsd,"NA","NA")
AUCPR <- c(trainaucpr,testaucpr,aucprdff,trainaucprsd,testaucprsd,basetr,basetest)
result <- rbind(AUC, AUCPR, deparse.level = 1)
rn <- c("train(mean)","test(mean)","diff(train-test)","train(sd)","test(sd)","train(baseline)","test(baseline)")


colnames(result) <- rn
print(result)


print(rft)
print(table(training$type))
print(table(testing$type))
print(prop.table(table(training$type)))
print(prop.table(table(testing$type)))

```



logistic regression model 1000 replicates

```{r}

fvarlg <- bufo_lgvar
d <- bufolist

outc <- "type"
envst <- append(fvarlg, outc)
   
fvarlgimplg <- list()
fvarlgmlg <- list()
fvarlgpredlg <- list()
fvarlgtrainsetlg <- list()

myauct <- list()
tlable <- list()
tune <- list()

################
auctrain <- list()
auctest <- list()
###############
for(i in 1:1000)
  {
     
    m <- d[[i]][ , envst]
    m$type <- factor(m$type)

  set.seed(110)
    
   Train <- createDataPartition(m$type, p = .7,list = FALSE,times = 1)

   training <- m[Train, ]
   
   
   training$type <- factor(training$type, levels = c("rk","random"))
   testing = m[ -Train, ]
   testing$type <- factor(testing$type, levels = c("rk","random"))

training_pv <- preProcess(training, method = c("center", "scale"))
trainTransformed <- predict(training_pv, training)
training <- trainTransformed

testing_pv <- preProcess(testing, method = c("center", "scale"))
testTransformed <- predict(testing_pv, testing)
testing <- testTransformed   

##############class weights
class_counts <- table(training$type)
n0 <- class_counts["random"]
n1 <- class_counts["rk"]
w0 <- 0.5 / n0
w1 <- 0.5 / n1

model_weights <- ifelse(training$type == "random",w0, w1)

 
train_control = trainControl(method="repeatedcv", number=2, repeats=5, savePredictions = T,summaryFunction = twoClassSummary, classProbs = TRUE)

 
 set.seed(396)
   mlg = train(training[,fvarlg],training[,outc],method="glm",family = "binomial", trControl=train_control, metric = "ROC", na.action = na.omit, maxit = 1000,weights =model_weights)
  #training
   Fitclgtr<- predict(mlg, training)
  conlgtr <- confusionMatrix(Fitclgtr, training$type,positive = "rk",mode = "everything")
  Fitplgtr <- predict(mlg, training,type = "prob")
  rocoblgtr <- prediction(Fitplgtr$rk, training$type, label.ordering = c("random", "rk"))
  
  #auc roc training
  aucroclgtr <- performance(rocoblgtr,"auc")
  auc1tr <- aucroclgtr@y.values[[1]]

#aucpr training
  aucprlgtr <- performance(rocoblgtr,"aucpr")
  auc2tr <- aucprlgtr@y.values[[1]]
  
  
  
  Fitplg <- predict(mlg, testing,type = "prob")
  rocoblg <- prediction(Fitplg$rk, testing$type, label.ordering = c("random", "rk"))

  aucroclg <- performance(rocoblg,"auc")
  auc1 <- aucroclg@y.values[[1]]

  aucprlg <- performance(rocoblg,"aucpr")
  auc2 <- aucprlg@y.values[[1]]
  
  vlg <- varImp(mlg)
  vlg <- as.data.frame(vlg$importance)
  names(vlg)[1] <- "fvarlg"
  vlgt <- data.frame(t(vlg))
  
 ###########################################################################  
  fvarlgimplg[[i]] <- vlgt
  fvarlgmlg[[i]] <- mlg
  fvarlgpredlg[[i]] <- Fitplg$rk
  fvarlgtrainsetlg[[i]] <- training
 ####################################################################  
 
vec <- c(auc1tr, auc2tr,auc1, auc2)
  myauct[[i]] <- vec
  tune[[i]] <- mlg$bestTune
 ################  
auctrain[[i]] <- auc1tr
auctest[[i]] <- auc1
####################    
}
auct <- as.data.frame(do.call(cbind, myauct))
aucct <- t(auct)
colnames(aucct) <- c("lgauc_train","lgaucpr_train","lgauc_test","lgaucpr_test")
 
aucct <- data.frame(aucct) 


p <- aucct
pt <- data.frame(t(p))

pt$mean <- apply(p,2,mean)
pt$sd <- apply(p,2,sd)

pt2c <- pt[,c(1001,1002)]
lgt <- as.data.frame(t(pt2c))

trainauc <- lgt[1,1]
trainaucpr <- lgt[1,2]
trainaucsd <- lgt[2,1]
trainaucprsd <- lgt[2,2]

testauc <- lgt[1,3]
testaucpr <- lgt[1,4]
testaucsd <- lgt[2,3]
testaucprsd <- lgt[2,4]

basetest <- prop.table(table(testing$type))[[1]]
basetr <- prop.table(table(training$type))[[1]]
aucdff <- trainauc-testauc
aucprdff <- trainaucpr-testaucpr


AUC <- c(trainauc,testauc,aucdff,trainaucsd,testaucsd,"NA","NA")
AUCPR <- c(trainaucpr,testaucpr,aucprdff,trainaucprsd,testaucprsd,basetr,basetest)
result <- rbind(AUC, AUCPR, deparse.level = 1)
rn <- c("train(mean)","test(mean)","diff(train-test)","train(sd)","test(sd)","train(baseline)","test(baseline)")


colnames(result) <- rn
print(result)


print(lgt)
print(table(training$type))
print(table(testing$type))
print(prop.table(table(training$type)))
print(prop.table(table(testing$type)))

```







