---
title: "paper2 bufo"
author: "irena"
date: "2024-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(infer)
library(xlsx)
library(fastDummies)
library(caret)
library(harmonicmeanp)
library(spatialRF)
```

load sxall.csv
```{r}

bufo <- filter(sxall, source=="survey",species =="Bufo bankorensis")
random <- filter(sxall, source=="random")

p <- bufo
##################################################
d <- nearZeroVar(p)
d1 <- d[!d<20]

sampf <- p[,-d1]

sampf$aspect_N <- factor(sampf$aspect_N, levels = c("0","1"))
sampf$aspect_S <- factor(sampf$aspect_S, levels = c("0","1"))
sampf$aspect_E <- factor(sampf$aspect_E, levels = c("0","1"))
#sampf$aspect_W <- factor(sampf$aspect_W, levels = c("0","1"))


randomf <- random[,-d1]

randomf$aspect_N <- factor(randomf$aspect_N, levels = c("0","1"))
randomf$aspect_S <- factor(randomf$aspect_S, levels = c("0","1"))
randomf$aspect_E <- factor(randomf$aspect_E, levels = c("0","1"))
#randomf$aspect_W <- factor(randomf$aspect_W, levels = c("0","1"))



set.seed(123)
r100p <- rep_sample_n(randomf, 234, replace = T, reps = 100, prob = NULL)
r100list <- split(r100p, r100p$replicate)

samplist <- list()

 for(j in 1:100){
         samplist[[j]] <- bind_rows(sampf, r100list[[j]])
 }

############################
bufolist <- samplist

colnames(bufolist[[3]])

##########################
set.seed(456)
r10p <- rep_sample_n(randomf, 234, replace = T, reps = 10, prob = NULL)
r10list <- split(r10p, r10p$replicate)

samplist <- list()

 for(j in 1:10){
         samplist[[j]] <- bind_rows(sampf, r10list[[j]])
 }

bufo10list <- samplist


```


```{r}
######################## Mann

ddset <- bufolist

pvalue <- list()

for(j in 1:100){
     
    dset <- ddset[[j]]

outputtest <- NULL
van <- colnames(dset[,c(20:180)])
dset$type <- as.factor(dset$type)
 for(i in c(20:180)){
    t1 <- wilcox.test(dset[,i]~dset$type,alternative = "two.sided")
    outputtest[i] <- t1$p.value
       }
pp <- outputtest[c(20:180)]

#names(pp) <- van
 pvalue[[j]] <- pp
 }
wop1 <- data.frame(pvalue)
 
 wop3 <- data.frame(t(wop1))
 colnames(wop3) <- van
 rownames(wop3) <- c(1:100)
 
################ chisquare
 
pvalue <- list() 
for(j in 1:100){
     
    dset <- ddset[[j]]

outputtest <- NULL
van <- colnames(dset[,c(181:183)])
dset$type <- as.factor(dset$type)
 for(i in c(181:183)){
    t2 <- table(dset$type,dset[,i])
     t3 <-chisq.test(t2)
    outputtest[i] <- t3$p.value
       }
pp <- outputtest[c(181:183)]

#names(pp) <- van
 pvalue[[j]] <- pp
 }
chop1 <- data.frame(pvalue)
 
 chop3 <- data.frame(t(chop1))
 colnames(chop3) <- van
 rownames(chop3) <- c(1:100)
 
###################################
 #univariate logistic

pvaout <- list()
coeout <- list()


for(j in 1:100){
d <- ddset[[j]][,c(12,20:180)]
van <- colnames(d)
formula_strings = sprintf("Ylogis ~ %s", van)
pva <-  NULL
coe <-  NULL
formula_strings = sprintf("Ylogis ~ %s", van)
 for(i in seq_along(van)){
    model = glm(as.formula(formula_strings[i]), data=d, family = binomial(link = 'logit'))
    sum <- summary(model)
    coeffs<- coef(sum)
     
     if (dim(coeffs)[[1]]==1) # if only one row of pvalues then NA
      {pva[i] <- NA
      }else 
          
      {
     
    pva[i] <- sum$coefficients[2,4]
    coe[i] <- sum$coefficients[2,1]
      }
  } 
pvaout[[j]] <-  pva[1:length(van)]
coeout[[j]] <-  coe[1:length(van)]
  #names(pvaout) <- van
 #names(coeout) <- van
 #all <- cbind(pvaout,coeout)
 #all1 <- data.frame(all)
 }

lgop1 <- data.frame(pvaout)
lgop3 <- data.frame(t(lgop1))
colnames(lgop3) <- van
rownames(lgop3) <- c(1:100)
 
```

```{r}
###################################

 whmp <- list()
 
 for(j in 1:ncol(wop3)){
     
    p <- wop3[,j]
 whmpvalue <- hmp.stat(p, w = NULL)
 whmp[[j]] <- whmpvalue

 }
 
 names(whmp) <- colnames(wop3)
 test <- data.frame(whmp)
 whmpt <- data.frame(t(test))
 whmpt$var <- rownames(whmpt)
 ###subset
  whmp010 <- filter(whmpt,hmp.stat <0.10)
 whmp005 <- filter(whmpt,hmp.stat <0.05)
 whmp001 <- filter(whmpt,hmp.stat <0.01)
 
 
 #######################
 
 chhmp <- list()
 
 for(j in 1:ncol(chop3)){
     
    p <- chop3[,j]
 chhmpvalue <- hmp.stat(p, w = NULL)
 chhmp[[j]] <- chhmpvalue

 }
 
 names(chhmp) <- colnames(chop3)
 test <- data.frame(chhmp)
 chhmpt <- data.frame(t(test))
 chhmpt$var <- rownames(chhmpt)
 ###subset
 
 chhmp010 <- filter(chhmpt,hmp.stat <0.10)
 chhmp005 <- filter(chhmpt,hmp.stat <0.05)
 
 
###################################33
 lghmp <- list()
 
 for(j in 1:ncol(lgop3)){
     
    p <- lgop3[,j]
 lghmpvalue <- hmp.stat(p, w = NULL)
 lghmp[[j]] <- lghmpvalue

 }
 
 names(lghmp) <- colnames(lgop3)
 test <- data.frame(lghmp)
 lghmpt <- data.frame(t(test))
 lghmpt$var <- rownames(lghmpt)
 
 ###subset
 lghmp010 <- filter(lghmpt,hmp.stat <0.10)
 lghmp005 <- filter(lghmpt,hmp.stat <0.05)
 lghmp001 <- filter(lghmpt,hmp.stat <0.01)
 lghmp025 <- filter(lghmpt,hmp.stat <0.025)
 
 
```

```{r}
 
 bufo_wv <- whmp005[,2]
 bufo_lgv <- lghmp005[,2]
 bufo_chv <- chhmp005[,2]
 bufo_v <- union(bufo_chv,union(bufo_wv,bufo_lgv))
 
 ch <- chhmp005
 colnames(ch) <- c("ch_hmp","var")
 
 w <- whmp005
 colnames(w) <- c("w_hmp","var")
 
 lg <- lghmp005
 colnames(lg) <- c("lg_hmp","var")
 
 
 test <- full_join(w, lg, by="var")
 
 bufo_vt <- full_join(test,ch, by="var")
 
 write.xlsx(bufo_vt,"C:\\GIS_working\\paper2\\bufo\\bufo_vt.xlsx")
 
```


```{r}
p <- sxall[,bufo_v]
pcor <- cor(p,method="spearman")
pcord <- as.data.frame(pcor)
write.xlsx(pcord,"C:\\GIS_working\\paper2\\bufo\\bufocor.xlsx")

#threshold 0.7
```


bufo_v:23, bufo_vf:17
```{r}
dele <- c("light_dw100","light_dw200","light_dw250","crop_dw050","house_dw150","house_dw250")

bufo_vf <- bufo_v[!bufo_v%in%dele]

```


vif
```{r}

tlist <- list()
for(i in 1:100){
    vifobj <- spatialRF::vif(bufolist[[i]][,bufo_vf])
    t <- filter(vifobj,vif>10)
    tlist[[i]] <- t
}
   
tlist

bufo_vff <- bufo_vf[!bufo_vf=="house_dw200"]

```


```{r}
save(bufolist,bufo_vf,bufo_vff,file="C:\\GIS_working\\paper2\\Rdata\\bufovar.RData")

load("C:\\GIS_working\\paper2\\Rdata\\bufovar.RData")
```




